### DISCUSSION TITLE
RTL-SDR stick not working in LXC + Docker with /dev/rtl_sdr mount under Proxmox

### DISCUSSION THREAD

**Discussion by Daniel-WW** [hertzg/rtl_433_docker#117] [Q&A] [answered]
Hi all,

I’m having trouble getting my RTL-SDR stick to work inside a Docker container that runs inside an unprivileged LXC on Proxmox.

Setup:  
- Proxmox VE 8.2  
- Unprivileged LXC container with Ubuntu 22.04  
- RTL-SDR stick (USB ID 0bda:2838) plugged into host  
- In the LXC config, I only use this line to mount the device:
```lxc.mount.entry: /dev/bus/usb/001/003 /dev/rtl_sdr none bind,optional,create=file```

The device `/dev/rtl_sdr` shows up inside the container (I can see it with `ls -l /dev/rtl_sdr`).

In Docker-compose, I pass the device like this:

```yaml
services:
  rtl433:
    image: hertzg/rtl_433
    devices:
      - /dev/rtl_sdr:/dev/rtl_sdr
    privileged: true
    restart: unless-stopped
```

In the rtl_433.conf file I just have `device 0` or i tried with `device /dev/rtl_sdr`, but the container keeps crashing right away. The logs don’t show any clear errors about missing device or permissions, it just restarts constantly.

Does anyone know what the correct config should be? Should the device path in the config be /dev/rtl_sdr or something else? Or is it even possible to use the stick like this in an unprivileged LXC + Docker setup?

Any help or hints would be appreciated, thanks!

If you want, I can help test or provide configs/logs. - Thanks and best Regards - Daniel
