### DISCUSSION TITLE
Multiple frequency and Hop

### DISCUSSION THREAD

**Discussion by bsmith76s** [hertzg/rtl_433_docker#29] [Q&A] [answered]
I have been trying to do multiple frequency in a docker-compose.yml. Does this docker container do multiple frequency like the native Merbanan install? if so I want to hop between 2 frequencys.

**Comment by hertzg** [comment, marked as answer]
Yes you can, the same way you would do without the docker container. All the commands that you write after `docker run hertzg/rtl_433` get passed directly to the rtl_433 executable.

This is already [documented in the readme under example usages section](https://github.com/hertzg/rtl_433_docker#example-usages)

### without docker
```
$ rtl_433 -f 433.92M -H 3 -f 420.92M -H 3
```

### using docker run
```
$ docker run hertzg/rtl_433 -f 433.92M -H 3 -f 420.92M -H 3
```

### using docker-compose (yaml)
```
services:
  rtl433:
    image: hertzg/rtl_433:latest
    command:
      - '-f433.92M'
      - '-H3'
      - '-f420.92M'
      - '-H3'
```
