### DISCUSSION TITLE
Shell script to start the container with the correct bus/device

### DISCUSSION THREAD

**Discussion by elmicha** [hertzg/rtl_433_docker#45] [Q&A] [answered]
Hi,

here is a simple shell script that can start the container with the correct USB bus and device.
User only need to change the `search="0bda:2838"` line.

```
#! /bin/bash
# see https://github.com/hertzg/rtl_433_docker

search="0bda:2838"
# or e.g. search="RTL2838", see output of lsusb

read bus device < <(
  lsusb |
    awk -v search="$search" '
      $0 ~ search { sub(/:/, "", $4); print $2, $4 }
    '
)
podman run --device /dev/bus/usb/$bus/$device hertzg/rtl_433 "$@"
```

**Comment by hertzg** [comment]
Hello, Thanks for sharing the script, some people might find it useful! I'll convert this to a discussion as this seems more like an `idea` then an issue.

Let's continue the discussion there. 👍

**Comment by hertzg** [comment]
There might be some undesired results when there are two dongles connected to the host (same vendor and device ids). For such cases you could use the serial from EEPROM to further narrow down the choice maybe?

**Comment by elmicha** [comment]
Ah yes, I didn't see the discussions tab.
Here is the script with optional search for the serial number.

```
#! /bin/bash
# see https://github.com/hertzg/rtl_433_docker

# search: something that should be searched in the output of lsusb
search="0bda:2838"

# If you have more than one device that is found with the search string,
# you can search for the serial number here.
# If not, set it to an empty string.
# You can set the serial number with rtl_eeprom and view it with
# rtl_eeprom or lsusb.
serial="rtl-sdr.com"

while read bus device ; do
  if [[ -n "$serial" ]] ; then
    iSerial=$(lsusb -D /dev/bus/usb/$bus/$device 2>/dev/null |
                awk '/iSerial/ { $1 = $2 = ""; sub(/^ +/, ""); print }'
           )
    if [[ "$iSerial" = "$serial" ]] ; then
      # echo "found $serial at $bus/$device" 1>&2
      break
    fi
  else
    # echo "found $search at $bus/$device" 1>&2
    break
  fi
done < <(
  lsusb |
    awk -v search="$search" '
      $0 ~ search { sub(/:/, "", $4); print $2, $4 }
    '
)

if [[ -z "$device" ]] ; then
  if [[ -n "$serial" ]] ; then    
    echo "device \"$search\" with serial \"$serial\" not found" 1>&2
  else
    echo "device \"$search\" not found" 1>&2
  fi
else
  podman run --device /dev/bus/usb/$bus/$device hertzg/rtl_433 "$@"
  # you can use podman or docker here
fi
```

**Comment by Vendo232** [comment]
Hello
I need this, I have 3 devices hooked to the Raspberry Pi, but only one shall be used for rtl_433. How do I use this script in real life?

Bus 001 Device 004: ID 0bda:2838 Realtek Semiconductor Corp. RTL2838 DVB-T ( sn#:1090 )
**Bus 001 Device 005: ID 0bda:2838 Realtek Semiconductor Corp. RTL2838 DVB-T ( sn#:00000001 ) / using this for rtl_433**
Bus 001 Device 003: ID 0bda:2838 Realtek Semiconductor Corp. RTL2838 DVB-T ( sn#:978 )
Bus 001 Device 002: ID 0bda:5411 Realtek Semiconductor Corp. RTS5411 Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

**Reply by hertzg** [reply]
In my case I have two of the same type of devices attached to a host that is running docker, and I use `docker-compose.yml` to run everything.

```
version: '3.8'

services:
  rtl_433_587:
    image: hertzg/rtl_433:alpine-3.14-21.05
    devices:
      - /dev/bus/usb
    container_name: rtl_433_587
    hostname: rtl_433_587
    restart: unless-stopped
    command:
      - '-d:${RTL_SERIAL_433_587}'
      - '-f433.587MHz'
      - '-Mtime:unix:usec:utc'
      - '-Mbits'
      - '-Mlevel'
      - '-Mprotocol'
      - '-Mstats:2:300'
      - '-Fmqtt://${MQTT_HOST},user=${MQTT_USER},pass=${MQTT_PASS}'
      - '-Finflux://${INFLUX_HOST}/api/v2/write?org=${INFLUX_ORG}&bucket=${INFLUX_BUCKET},token=${INFLUX_TOKEN}'

  rtl_433_920:
    image: hertzg/rtl_433:alpine-3.14-21.05
    devices:
      - /dev/bus/usb
    container_name: rtl_433_920
    hostname: rtl_433_920
    restart: unless-stopped
    command:
      - '-d:${RTL_SERIAL_433_92}'
      - '-f433.92MHz'
      - '-Mtime:unix:usec:utc'
      - '-Mbits'
      - '-Mlevel'
      - '-Mprotocol'
      - '-Mstats:2:300'
      - '-Fmqtt://${MQTT_HOST},user=${MQTT_USER},pass=${MQTT_PASS}'
      - '-Finflux://${INFLUX_HOST}/api/v2/write?org=${INFLUX_ORG}&bucket=${INFLUX_BUCKET},token=${INFLUX_TOKEN}'
``` 

In my case the devices might be mounted with any bus/id pair and I let `rtl_433` do the selection of the correct one using it's serial number.

The only downside is that I am exposing the whole `/dev/bus/usb` to the container but I have this host (VM) dedicated only for rtl_433

```
root@rtl433 [ ~ ]# lsusb
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 006: ID 0bda:2838 Realtek Semiconductor Corp. RTL2838 DVB-T
Bus 001 Device 005: ID 0e0f:0002 VMware, Inc. Virtual USB Hub
Bus 001 Device 004: ID 0e0f:0002 VMware, Inc. Virtual USB Hub
Bus 001 Device 003: ID 0bda:2838 Realtek Semiconductor Corp. RTL2838 DVB-T
Bus 001 Device 002: ID 0e0f:0003 VMware, Inc. Virtual Mouse
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```
