### DISCUSSION TITLE
Using custom config

### DISCUSSION THREAD

**Discussion by gcormier** [hertzg/rtl_433_docker#78] [Show and tell]
Took me a bit so I figured I would post here to share. To get a custom conf file going, I dug up the path where they were present inside the container, which is `/usr/local/etc/rtl_433/`. This works for me for my Reolink camera.

```
 rtl433:
    container_name: rtl433
    image: hertzg/rtl_433:alpine-latest-master
    devices:
      - /dev/bus/usb
    command:
      - "-R"
      - "40"
      - "-R"
      - "30"  # Reolink doorbell EV1527
      - "-c"
      - "/usr/local/etc/rtl_433/Reolink-doorbell.conf"
      - "-R"
      - "176:12080"
      - "-F"
```
