### ISSUE TITLE
Error gathering device information with a RTL_TCP device in the "devices:" section

### ISSUE THREAD

**Issue by phrxmd** [hertzg/rtl_433_docker#115]
I'm using a tuner on another machine that I'm accessing via RTL_TCP. When I try to set up the Docker container as follows...

```yaml
version: "3"
services:
  rtl433:
    image: hertzg/rtl_433:latest
    devices:
      - rtl_tcp:192.168.0.1:1234
    command:
      - -f
      - 433.92M
networks: {}
```

...I get an error message upon deployment:
```
Error response from daemon: error gathering device information while adding custom device "rtl_tcp": no such file or directory
```

It does work when I drop the `devices:` section altogether and move the device declaration into the command line:
```yaml
version: "3"
services:
  rtl433:
    image: hertzg/rtl_433:latest
    command:
      - -d
      - rtl_tcp:192.168.0.1:1234
      - -f
      - 433.92M
networks: {}
```

I guess there is something about the handling of the `devices:` section upon deployment that breaks if it doesn't point to something in the device tree.
