### ISSUE TITLE
Command not working properly

### ISSUE THREAD

**Issue by gcormier** [hertzg/rtl_433_docker#5]
Unable to pass parameters it would seem.

Locally
```
/build/src/rtl_433 -R40 -R176:12080 -Fmqtt://192.168.1.33:1883,user=mqtt,pass=mqtt123,retain=0,devices=rtl_433[/model][/subtype][/channel][/id]
rtl_433 version 20.11-72-g914552b9 branch master at 202102121205 inputs file rtl_tcp RTL-SDR
Use -h for usage help and see https://triq.org/ for documentation.
Trying conf file at "rtl_433.conf"...
Trying conf file at "/home/greg/.config/rtl_433/rtl_433.conf"...
Trying conf file at "/usr/local/etc/rtl_433/rtl_433.conf"...
Trying conf file at "/etc/rtl_433/rtl_433.conf"...
Publishing MQTT data to 192.168.1.33 port 1883
Publishing device info to MQTT topic "rtl_433[/model][/subtype][/channel][/id]".
Registered 2 out of 178 device decoding protocols [ 40 ]
Detached kernel driver
Found Rafael Micro R820T tuner
Exact sample rate is: 250000.000414 Hz
[R82XX] PLL not locked!
Sample rate set to 250000 S/s.
Tuner gain set to Auto.
Tuned to 433.920MHz.
Allocating 15 zero-copy buffers
MQTT Connected...
MQTT Connection established.
```

docker-compose:
```
  rtl433:
    container_name: rtl433
    image: hertzg/rtl_433:latest
    devices:
      - /dev/bus/usb
    command:
      - "-R40 -R176:12080 -Fmqtt://192.168.1.33:1883,user=mqtt,pass=mqtt123,retain=0,devices=rtl_433[/model][/subtype][/channel][/id]"
      #- "-R40"
      #- "-R176:12080"
      #- "-Fmqtt://192.168.1.33:1883,user=mqtt,pass=mqtt123,retain=0,devices=rtl_433[/model][/subtype][/channel][/id]"
    restart: unless-stopped
```

```
...
rtl433         | rtl_433 version 20.11 branch  at 202011122224 inputs file rtl_tcp RTL-SDR
rtl433         | Use -h for usage help and see https://triq.org/ for documentation.
rtl433         | Trying conf file at "rtl_433.conf"...
rtl433         | Trying conf file at "/root/.config/rtl_433/rtl_433.conf"...
rtl433         | Trying conf file at "/usr/local/etc/rtl_433/rtl_433.conf"...
rtl433         | Trying conf file at "/etc/rtl_433/rtl_433.conf"...
rtl433         | Protocol [40] "Acurite 592TXR Temp/Humidity, 5n1 Weather Station, 6045 Lightning, 3N1, Atlas" does not take arguments "12080 -F mqtt://192.168.1.33:1883,user=mqtt,pass=mqtt123,retain=0,devices=rtl_433[/model][/subtype][/channel][/id]"!
rtl433         | Registered 1 out of 175 device decoding protocols [ 40 ]
rtl433         | Detached kernel driver
```

I have tried both the single line in docker-compose as well as one parameter per line with the same results.

**Comment by hertzg** [comment]
Try passing each space sparated part as a new entry in docker compose:
```
  rtl433:
    container_name: rtl433
    image: hertzg/rtl_433:latest
    devices:
      - /dev/bus/usb
    command:
      - "-R"
      - "40"
      - "-R"
      - "176:12080"
      - "-F"
      - "mqtt://192.168.1.33:1883,user=mqtt,pass=mqtt123,retain=0,devices=rtl_433[/model][/subtype][/channel][/id]"
    restart: unless-stopped
```


This is what mine looks like:
```
  rtl_433:
    container_name: rtl_433
    image: hertzg/rtl_433:latest
    restart: unless-stopped
    devices:
      - "/dev/bus/usb/001/003"
    command:
      - "-d"
      - "rtl_tcp://rtl_tcp:1234"
      - "-M"
      - "time:unix:usec:utc"
      - "-M"
      - "bits"
      - "-M"
      - "level"
      - "-M"
      - "protocol"
      - "-M"
      - "stats:2:300"
      - "-F"
      - "mqtt://redacted:1883,retain=1"
      - "-F"
      - "influx://redacted:8086/write?db=rtl433"
```
