### ISSUE TITLE
Invalid PSK settings for TLS MQTT

### ISSUE THREAD

**Issue by metrafonic** [hertzg/rtl_433_docker#68]
There is an issue using TLS for MQTT connections, which is only present on this docker implementation of rtl_433. 
See https://github.com/merbanan/rtl_433/issues/1569#issuecomment-1421041867

I am unable to replicate the issue outside of this docker image

docker-compose.yml:
```
version: '3'
services:
  rtl433:
    image: hertzg/rtl_433:latest
    devices:
      - '/dev/bus/usb/001/006'
    command:
      - '-Mtime:unix:usec:utc'
      - '-Mbits'
      - '-Mlevel'
      - '-Mprotocol'
      - '-Mstats:2:300'
      - '-Fmqtts://xxxxx:8883,user=xxxx,pass=xxxx'
    restart: always
```

Output:
```
rtl_433-rtl433-1  | rtl_433 version 22.11 (2022-11-19) inputs file rtl_tcp RTL-SDR with TLS
rtl_433-rtl433-1  | Use -h for usage help and see https://triq.org/ for documentation.
rtl_433-rtl433-1  | Trying conf file at "rtl_433.conf"...
rtl_433-rtl433-1  | Trying conf file at "/root/.config/rtl_433/rtl_433.conf"...
rtl_433-rtl433-1  | Trying conf file at "/usr/local/etc/rtl_433/rtl_433.conf"...
rtl_433-rtl433-1  | Trying conf file at "/etc/rtl_433/rtl_433.conf"...
rtl_433-rtl433-1  | Publishing MQTT data to xxxxxxxxxxxxx port 8883 (TLS)
rtl_433-rtl433-1  | Publishing device info to MQTT topic "rtl_433/xxxxx/devices[/type][/model][/subtype][/channel][/id]".
rtl_433-rtl433-1  | Publishing events info to MQTT topic "rtl_433/xxxxx/events".
rtl_433-rtl433-1  | Publishing states info to MQTT topic "rtl_433/xxxxx/states".
rtl_433-rtl433-1  | MQTT connect (xxxxxxxxxxx:8883) failed: Invalid PSK settings
```
