### ISSUE TITLE
rtl_433 v22.11 not passing "-R" device flags correctly

### ISSUE THREAD

**Issue by dlasher** [hertzg/rtl_433_docker#81]
ARCH: AMD64
OS: Debian 11 (Dietpi)
PROBLEM: rtl_433 not honoring individual device enable/disables passed via -R flag. Tried both as command: and :environment.

docker-compose:
```
version: '3'
services:
  rtl433:
    image: hertzg/rtl_433:latest
    restart: unless-stopped
    container_name: rtl_433
    hostname: rtl_433

    devices:
      - '/dev/bus/usb'
    command:
      - '-Mtime:unix:usec:utc'
      - '-Mbits'
      - '-Mlevel'
      - '-Mprotocol'
      - '-Mstats:2:300'
      - '-Yautolevel'
      - '-R-59 -R-60 -R-82 -R-88 -R-89 -R-90 -R-95 -R-110 -R-123 -R-140 -R-156 -R-168 -R-180 -R-186 -R-201 -R-203 -R-208 -R-212 -R-225 -R-226 -R-241'
    environment:
      - '-d :00005555'
      - '-R-59 -R-60 -R-82 -R-88 -R-89 -R-90 -R-95 -R-110 -R-123 -R-140 -R-156 -R-168 -R-180 -R-186 -R-201 -R-203 -R-208 -R-212 -R-225 -R-226 -R-241'
 ```

Output from started docker container
 ```
Use -h for usage help and see https://triq.org/ for documentation.
Trying conf file at "rtl_433.conf"...
Trying conf file at "/root/.config/rtl_433/rtl_433.conf"...
Trying conf file at "/usr/local/etc/rtl_433/rtl_433.conf"...
Trying conf file at "/etc/rtl_433/rtl_433.conf"...
Publishing MQTT data to 10.4.10.162 port 1883
Publishing device info to MQTT topic "rtl_433/rtl_433/devices[/type][/model][/subtype][/channel][/id]".
Publishing events info to MQTT topic "rtl_433/rtl_433/events".
Publishing states info to MQTT topic "rtl_433/rtl_433/states".
Registered 190 out of 223 device decoding protocols [ 1-4 8 11-12 15-17 19-23 25-26 29-36 38-58 60 63 67-71 73-100 102-105 108-116 119 121 124-128 130-149 151-161 163-168 170-175 177-197 199 201-215 217-223 ]
Found Rafael Micro R820T/2 tuner
Exact sample rate is: 250000.000414 Hz
Sample rate set to 250000 S/s.
Tuner gain set to Auto.
Tuned to 433.920MHz.
Allocating 15 zero-copy buffers
MQTT Connected...
```

Notice that the devices prohibited are being used (186 for example).

When I invoke rtl_433 from the CLI - with those command line switches, it correctly removes those.

```
build/src/rtl_433 -D restart -R-59 -R-60 -R-82 -R-88 -R-89 -R-90 -R-95 -R-110 -R-123 -R-140 -R-156 -R-168 -R-180 -R-186 -R-201 -R-203 -R-208 -R-212 -R-225 -R-226 -R-241 -Mtime:unix:usec:utc -Mbits -Mlevel -Mprotocol -Mstats:2:300 -d :00000978 -Y autolevel

....
[Protocols] Registered 191 out of 245 device decoding protocols [ 1-4 8 10-12 15-17 19-23 25-26 29-36 38-58 63 67-71 73-81 83-87 91-94 96-100 102-105 108-109 111-116 119-121 124-128 130-139 141-149 151-155 157-161 163-167 170-175 177-179 181-185 187-197 199 202 204-2
```

Might be related to : https://github.com/hertzg/rtl_433_docker/issues/63
