### ISSUE TITLE
Container isn't working, local runs fine

### ISSUE THREAD

**Issue by gcormier** [hertzg/rtl_433_docker#83]
Sorry I don't have a better title. My power monitoring (Blueline) has stopped working inside the container.

# Locally
I've pulled the latest master from git, compiled, and it works fine.

```
./rtl_433 -R 40 -R 176:12080 -F mqtt://192.168.1.33,user=mqtt,pass=ABC123,retain=0,devices=rtl_433[/model][/subtype][/channel][/id]
rtl_433 version nightly-4-g767e5387 branch master at 202306081919 inputs file rtl_tcp RTL-SDR
Use -h for usage help and see https://triq.org/ for documentation.
Trying conf file at "rtl_433.conf"...
Trying conf file at "/home/greg/.config/rtl_433/rtl_433.conf"...
Trying conf file at "/usr/local/etc/rtl_433/rtl_433.conf"...
Trying conf file at "/etc/rtl_433/rtl_433.conf"...
MQTT: Publishing MQTT data to 192.168.1.33 port 1883
MQTT: Publishing device info to MQTT topic "rtl_433[/model][/subtype][/channel][/id]".
Use "-F log" if you want any messages, warnings, and errors in the console.
Detached kernel driver
Found Rafael Micro R820T tuner
Exact sample rate is: 250000.000414 Hz
[R82XX] PLL not locked!
Allocating 15 zero-copy buffers
```
```
ps aux | grep rtl
greg     2399931  2.4  0.0 131984  5888 pts/0    Sl+  11:46   0:00 ./rtl_433 -R 40 -R 176:12080 -F mqtt://192.168.1.33 user mqtt pass ABC123 retain 0 devices rtl_433[/model][/subtype][/channel][/id]
```
Pulses showing up in MQTT-explorer from BOTH my power monitor as well as my thermometer.
![image](https://github.com/hertzg/rtl_433_docker/assets/8388983/38cd3ade-9df9-4fb8-afe6-3342f6994d9f)

# Container
If I stop the process above and switch to a container,

```
  rtl433:
    container_name: rtl433
    image: hertzg/rtl_433:master
    devices:
      - /dev/bus/usb
    command:
      - "-R"
      - "40"
      - "-R"
      - "176:12080"
      - "-F"
      - "mqtt://192.168.1.33,user=mqtt,pass=ABC123,retain=0,devices=rtl_433[/model][/subtype][/channel][/id]"
    restart: unless-stopped
```

```
docker exec -it rtl433 ash
~ # ps 
PID   USER     TIME  COMMAND
    1 root      0:00 /usr/local/bin/rtl_433 -R 40 -R 176:12080 -F mqtt://192.168.1.33 user mqtt pass mqtt123 retain 0 devices rtl_433[/model][/subtype][/channel][/id]
```

The power messages no longer appear. The temperature sensor messages *continue* to appear.
![image](https://github.com/hertzg/rtl_433_docker/assets/8388983/85e76311-0ae2-48d1-a212-46c42a382628)

I have tried both `hertzg/rtl_433:master` and `hertzg/rtl_433:latest` with the same issue. My container setup was working without any hiccups at all until May 30th.
