### ISSUE TITLE
No input driver for SoapySDR compiled in

### ISSUE THREAD

**Issue by nbcomaf** [hertzg/rtl_433_docker#96]
I'm tearing my hair out trying to get this working. I have two identical RTL2838 dongles, exactly the same as @hertzg - and I've been trying to folllow [this post](https://github.com/hertzg/rtl_433_docker/issues/14#issuecomment-989288405) to get two containers working with different frequencies. At first I had the issue of identical serial numbers so changed it on one of them. Now, whatever I try to do will not successfully start the container.

I had a single container working fine but adding the second seems to have messed things up somewhere. I now can't even go back to a single container with the previously working config. And I've tried so many things - I feared I may have somehow busted the dongles but have managed to confirm they are fine and get messages to my MQTT server by using native rtl_433 installed direct on my Ubuntu server.

What I think is the main issue is for some reason using `-d :[serial number]` in my docker-compose.yaml seems to force the container to try and run as SoapySDR. 

```
rtl_433 version 22.11 (2022-11-19) inputs file rtl_tcp RTL-SDR with TLS
Use -h for usage help and see https://triq.org/ for documentation.
Trying conf file at "rtl_433.conf"...
Trying conf file at "//.config/rtl_433/rtl_433.conf"...
Trying conf file at "/usr/local/etc/rtl_433/rtl_433.conf"...
Trying conf file at "/etc/rtl_433/rtl_433.conf"...
MQTT: Publishing MQTT data to 192.168.1.130 port 1883
MQTT: Publishing device info to MQTT topic "rtl_433/OilSonicWatchman".
[Protocols] Registered 212 out of 246 device decoding protocols [ 1-4 8 10-12 15-17 19-23 25-26 29-36 38-60 63 67-71 73-100 102-105 108-116 119-121 124-128 130-149 151-161 163-168 170-175 177-197 199 201-215 217-228 230-232 234-241 243-244 246 ]
[sdr_open] No input driver for SoapySDR compiled in.
```

And my docker-compose.yaml:

``` 
rtl_433:
    container_name: rtl_433
    image: ghcr.io/hertzg/rtl_433_docker:master
    user: 1000:1000
    environment:
      - TZ=Europe/London
    volumes:
      - /opt/smarthome/rtl_433:/etc/rtl_433
    devices:
      # - /dev/bus/usb/003/007
      - /dev/bus/usb
    command:
      - '-d :00000002'
      - '-f433.92M'
      - '-Fkv'
      - '-Csi'
      - '-Fmqtt://192.168.1.130:1883,user=XXXX,pass=XXXX,retain=1,devices=rtl_433/OilSonicWatchman'
```

Things I've tried:
- Modprobe blocklist, or not
- Udev rtl-sdr.rules
- Restarting the server and unplugging/replugging dongles at various times
- Different USB ports
- Setting in config file vs from docker-compose commands
- Different builds including specific version numbers

Can anyone shed some light on what I could maybe try next? I had a single dongle working fine but don't want gaps in my weather station data from a hop interval!

Many thanks in advance.
