### ISSUE TITLE
Unable to get -v or -vv to work when there are multiple arguments for rtl_433

### ISSUE THREAD

**Issue by xconverge** [hertzg/rtl_433_docker#99]
I am wondering if I am doing something silly here but here are 3 scenarios, with the 3rd one not working correctly. I also have tried putting the -vv along with the mqtt argument and tried multiple permutations.

MQTT works when it is the only argument

```
    rtl433:
        container_name: rtl433
        image: hertzg/rtl_433:latest-debian
        environment:
            - TZ=${TZ}
        devices:
            - "/dev/bus/usb/001/002"
        command:
            - "-Fmqtt://eclipse-mosquitto:1883,retain=1,devices=rtl_433[/model][/id]"
        restart: always
```

-vv works when it is the only argument

```
    rtl433:
        container_name: rtl433
        image: hertzg/rtl_433:latest-debian
        environment:
            - TZ=${TZ}
        devices:
            - "/dev/bus/usb/001/002"
        command:
            - "-vv"
        restart: always
```

Only MQTT works when both are supplied and I cannot get verbosity to adjust or apply at all (this is the one I want to work and cannot get working)

```
    rtl433:
        container_name: rtl433
        image: hertzg/rtl_433:latest-debian
        environment:
            - TZ=${TZ}
        devices:
            - "/dev/bus/usb/001/002"
        command:
            - "-vv"
            - "-Fmqtt://eclipse-mosquitto:1883,retain=1,devices=rtl_433[/model][/id]"
        restart: always
```
